language: php

sudo: false

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
  - LARAVEL=5.0.* TESTBENCH=3.0.* PHPUNIT=4.8.*
  - LARAVEL=5.1.* TESTBENCH=3.1.* PHPUNIT=5.7.*
  - LARAVEL=5.2.* TESTBENCH=3.2.* PHPUNIT=5.7.*
  - LARAVEL=5.3.* TESTBENCH=3.3.* PHPUNIT=5.7.*
  - LARAVEL=5.4.* TESTBENCH=3.4.* PHPUNIT=5.7.*
  - LARAVEL=5.5.* TESTBENCH=3.5.* PHPUNIT=~6.0

matrix:
  exclude:
    - php: 7.2
      env: LARAVEL=5.0.* TESTBENCH=3.0.* PHPUNIT=4.8.*

before_install:
  - composer self-update --stable --no-interaction
  - composer require laravel/framework:$LARAVEL orchestra/testbench:$TESTBENCH phpunit/phpunit:$PHPUNIT --no-update --no-interaction --dev

install:
  - travis_retry composer update --no-suggest --no-interaction
  - composer info

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
